# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
flutter_application_path = '../my_flutter'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'TestFlutterModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestFlutterModule
  install_all_flutter_pods(flutter_application_path)

end
